services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    command: ["-js", "-c", "/nats/nats-server.conf"]
    volumes:
      - ./nats-config/nats-server.conf:/nats/nats-server.conf
      - ./nats-config/nsc/jwt:/nsc/jwt:ro